{% set name = "pyeda" %}
{% set version = "0.28.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07185f458d5d0b2ba5058da8b95dad6ab7684ceaf41237a25bcd3f005490f59d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - CFLAGS=-Wno-incompatible-pointer-types

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - crossenv                            # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyeda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cjdrake/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python Electronic Design Automation

extra:
  recipe-maintainers:
    - lorenzleutgeb
